fix: Remove duplicate WebviewIntentProvider
cozy/cozy-bar pull request #805
Opened 2022-12-08 13:58 UTC by zatteo

WebviewIntentProvider is already added in apps using the bar.

2022-12-08 14:05 UTC, Crash-- commented on src/index.jsx
> -import { WebviewIntentProvider } from 'cozy-intent'
Can you remove it from the package.json ?

2022-12-08 14:26 UTC, acezard requested changes

2022-12-08 14:26 UTC, acezard commented on package.json
> -    "cozy-intent": "^1.7.0",
test/build will be broken if `cozy-ui@77.9.1` doesn't have access to `cozy-intent`

2022-12-08 15:51 UTC, Crash-- approved these changes

2022-12-09 09:47 UTC, acezard approved these changes

2022-12-09 09:47 UTC, merged